export enum CardType {
  AMERICAN_EXPRESS = 0,
  DINERS = 1,
  DINERS_CARTE_BLANCHE = 2,
  DISCOVER_CLUB = 3,
  CHINA_UNIONPAY = 4,
  JCB = 5,
  LASER = 6,
  MAESTRO = 7,
  MASTERCARD = 8,
  VISA_ELECTRON = 9,
  VISA = 10,
}
